=== grishmaukani/7th-Sem-Lab-Files/WDM/P3/gtustudent.dtd
<!ELEMENT students(student*)>
<!ELEMENT student(name, city, admissionyear, CPI)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT admissionyear (#PCDATA)>
<!ELEMENT CPI (#PCDATA)>

<!ATTLIST student branch (COMPUTER|MECHANICAL|CHEMICAL|INFORMATIONTECHNOLOGY|CIVIL) #REQUIRED>

=== grishmaukani/7th-Sem-Lab-Files/WDM/P3/gtustudent.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE student SYSTEM "gtustudent.dtd">

<students>
	<student branch="COMPUTER">
		<name>Abdul Quadir</name>
		<city>Ahmedabad</city>
		<admissionyear>2009</admissionyear >
		<CPI>7.5</CPI>
	</student>
	
	<student branch="MECHANICAL">
		<name>Joseph Desusa</name>
		<city>Baroda</city>
		<admissionyear>2009</admissionyear >
		<CPI>8.5</CPI>
	</student>
	
	<student branch="CHEMICAL">
		<name>Sanjay Patel </name>
		<city>Surat</city>
		<admissionyear>2008</admissionyear >
		<CPI>6.5</CPI>
	</student>
	
	<student branch="COMPUTER">
		<name>Riya Sharma</name>
		<city>Baroda</city>
		<admissionyear>2009</admissionyear >
		<CPI>7.0</CPI>
	</student>
	
	<student branch="INFORMATIONTECHNOLOGY">
		<name>Sudha Patel</name>
		<city>Ahmedabad</city>
		<admissionyear>2009</admissionyear >
		<CPI>7.3</CPI>
	</student>
	
	<student branch="CIVIL">
		<name>Akhilesh yadav</name>
		<city>Mehsana</city>
		<admissionyear>2008</admissionyear >
		<CPI>6.0</CPI>
	</student>
</students>
